### ISSUE TITLE
Table is crashing, if searchable is true in grouped table

### ISSUE THREAD

**Issue by Naavukarasan** [saisandeepvaddi/ant-table-extensions#73]
![image](https://user-images.githubusercontent.com/46783622/96579566-b13fca00-12f4-11eb-8a63-740335d2eb94.png)
![image](https://user-images.githubusercontent.com/46783622/96579699-e3512c00-12f4-11eb-951c-15ec8e59e98d.png)
As mentioned in the title, if i enable search in grouped table, the page is getting crashed.

More info about grouping head:
https://ant.design/components/table/#components-table-demo-grouping-columns

**Comment by saisandeepvaddi** [comment]
Can you please try v1.1.6.

**Comment by Naavukarasan** [comment]
Thank you for the quick response. The issue is fixed.
